[package]
name = "shadcn_showcase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
arkit = { workspace = true, features = ["shadcn"] }
napi-ohos.workspace = true
napi-derive-ohos.workspace = true

[build-dependencies]
napi-build-ohos.workspace = true
