[package]
name = "arkit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arkit_derive.workspace = true
arkit_runtime.workspace = true
arkit_arkui.workspace = true
arkit_prelude.workspace = true
arkit_hooks.workspace = true
arkit_i18n.workspace = true
arkit_i18n_macros.workspace = true
arkit_router.workspace = true
arkit_animation.workspace = true
arkit_shadcn.workspace = true
arkit_icon.workspace = true
ohos-arkui-binding.workspace = true
openharmony-ability.workspace = true
napi-ohos.workspace = true
napi-derive-ohos.workspace = true
