[package]
name = "arkit"
description = "Dioxus-based ArkUI application framework for OpenHarmony"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
full = ["animation", "chart", "i18n", "icon", "router", "shadcn"]
animation = ["dep:arkit_animation"]
chart = ["animation", "dep:arkit_chart"]
i18n = ["dep:arkit_i18n"]
icon = ["dep:arkit_icon"]
router = ["animation", "dep:arkit_router"]
shadcn = ["animation", "icon", "dep:arkit_shadcn"]

[dependencies]
arkit_derive.workspace = true
arkit_runtime.workspace = true
arkit_arkui.workspace = true
arkit_prelude.workspace = true
arkit_hooks.workspace = true
arkit_i18n = { workspace = true, optional = true }
arkit_router = { workspace = true, optional = true }
arkit_animation = { workspace = true, optional = true }
arkit_chart = { workspace = true, optional = true }
arkit_shadcn = { workspace = true, optional = true }
arkit_icon = { workspace = true, optional = true }
ohos-arkui-binding.workspace = true
openharmony-ability.workspace = true
napi-ohos.workspace = true
napi-derive-ohos.workspace = true
