[package]
name = "async_task"
description = "Async task and Dioxus resource example for Arkit"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit.workspace = true
tokio = { workspace = true, features = ["time"] }

