[package]
name = "async_task"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
arkit.workspace = true
tokio = { workspace = true, features = ["time"] }
napi-ohos.workspace = true
napi-derive-ohos.workspace = true

[build-dependencies]
napi-build-ohos.workspace = true
