/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function disposeAllRenders(): void

/**
  * r" Releases only the matching Ability-session transport. A stale
  * r" owner cannot clear endpoints installed for a later session.
  */
export declare function disposeBridge(bridgeOwner: string): void

export declare function disposeRender(renderOwner: string): void

export declare function init(bindings: object, bridgeOwner: string, context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function render(slot: NodeContent, renderOwner: string): void
