[package]
name = "arkit_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_arkui.workspace = true
arkit_elements.workspace = true
dioxus-core.workspace = true
ohos-arkui-binding.workspace = true
ohos-hilog-binding.workspace = true
openharmony-ability = { workspace = true, features = ["webview"] }
napi-ohos.workspace = true
tokio.workspace = true
