[package]
name = "arkit_icon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_prelude.workspace = true
arkit_arkui.workspace = true
rust-embed.workspace = true
ohos-display-binding.workspace = true
rustc-hash.workspace = true
