//! WebView capability through the `ohos.webview` bridge plugin.
//!
//! The `webview` feature compiles the pluginized WebView facade from
//! `openharmony-ability-plugin-webview`. The framework owns the whole plugin
//! lifecycle so integrators stay unaware of it:
//!
//! 1. [`inject_webview_plugins`] registers the Rust-side `WebviewBridgePlugin`
//!    during the ability-init stage (generated by the `#[entry]` macro), so
//!    the plugin is live before any ArkTS lifecycle event is delivered.
//! 2. The generated `#[entry]` init installs the Ability-session bridge;
//!    [`RuntimeHandle::webview`] then hands out a lazily-cached
//!    [`WebviewClient`] when the dioxus root is rendered.
//! 3. The ArkTS host (`@ohos-rs/ability-plugin-webview` WebviewPlugin) mounts
//!    the WebView FrameNode into the session root — either full-bleed, under
//!    a caller-provided `ohos.node` container, or positioned with the
//!    `WebviewStyle` `x`/`y`/`width`/`height` (numbers are vp, strings are
//!    ArkUI lengths such as "30%"). The Web engine initializes at
//!    `ui-context-ready`.
//!
//! The old helper-based embedded WebView (`createEmbeddedWebview` + native
//! child mounts) does not exist on the pluginized mainline; the WebView
//! surface lives in the ArkTS session tree and the bridge contract carries
//! only opaque container handles from the built-in `ohos.node` plugin.

use std::sync::Once;

use napi_ohos::Result;
use openharmony_ability::OpenHarmonyApp;

pub use openharmony_ability_plugin_webview::{
    WebviewBridgePlugin, WebviewCallbacksBuilder, WebviewClient, WebviewCreateRequest,
    WebviewHandle, WebviewJavascriptProxyBuilder, WebviewProtocol, WebviewProtocolOptions,
    WebviewProtocolRequest, WebviewProtocolResponse, WebviewStyle,
};

static WEBVIEW_PLUGIN: Once = Once::new();

/// Registers the `ohos.webview` Rust plugin facade on the shared ability.
///
/// Injected by the `#[entry]` generated `init` — the earliest lifecycle stage
/// reachable from Rust (ability-create). Idempotent per process: the plugin
/// contract is registered at most once, later calls are no-ops. Must run
/// before the generated init returns the plugin declarations and the ArkTS
/// host starts delivering plugin events.
pub fn inject_webview_plugins(app: &OpenHarmonyApp) -> Result<()> {
    let mut outcome = None;
    WEBVIEW_PLUGIN.call_once(|| {
        outcome = Some(app.register_plugin(WebviewBridgePlugin));
    });
    // Only the first call registers; subsequent calls observe no outcome and
    // therefore report success.
    outcome.unwrap_or(Ok(()))
}
