[package]
name = "arkit_arkui"
description = "Dioxus renderer for native OpenHarmony ArkUI nodes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_elements.workspace = true
dioxus-core.workspace = true
ohos-arkui-binding.workspace = true
ohos-hilog-binding.workspace = true
rustc-hash.workspace = true
