//! Shadcn component registry — 50 components migrated from the original Elm
//! builder API to dioxus 0.7 `#[component]` + `rsx!`.
//!
//! Each component preserves its original styling logic (colors/radii/spacing/
//! typography/shadow) but renders via dioxus elements instead of the old
//! `Component`/`Element` builder.

pub(crate) const ARKUI_BUTTON_TYPE_NORMAL: i32 = 0;
pub(crate) const ARKUI_BORDER_STYLE_SOLID: i32 = 0;

mod accordion;
mod alert;
mod alert_dialog;
mod aspect_ratio;
mod avatar;
mod badge;
mod breadcrumb;
mod button;
mod calendar;
mod card;
mod carousel;
mod chart;
mod checkbox;
mod collapsible;
mod combobox;
mod command;
mod context_menu;
mod date_picker;
mod dialog;
mod drawer;
mod dropdown_menu;
mod floating_layer;
mod form;
mod hover_card;
mod input;
mod input_otp;
mod label;
mod menu_common;
mod menubar;
mod navigation_menu;
mod pagination;
mod popover;
mod progress;
mod radio_group;
mod resizable;
mod scroll_area;
mod select;
mod separator;
mod sheet;
mod sidebar;
mod skeleton;
mod slider;
mod surfaces;
mod switch;
mod table;
mod tabs;
mod text;
mod textarea;
mod toggle;
mod toggle_group;
mod tooltip;

pub use accordion::*;
pub use alert::*;
pub use alert_dialog::*;
pub use aspect_ratio::*;
pub use avatar::*;
pub use badge::*;
pub use breadcrumb::*;
pub use button::*;
pub use calendar::*;
pub use card::*;
pub use carousel::*;
pub use chart::*;
pub use checkbox::*;
pub use collapsible::*;
pub use combobox::*;
pub use command::*;
pub use context_menu::*;
pub use date_picker::*;
pub use dialog::*;
pub use drawer::*;
pub use dropdown_menu::*;
pub use floating_layer::*;
pub use form::*;
pub use hover_card::*;
pub use input::*;
pub use input_otp::*;
pub use label::*;
pub use menu_common::*;
pub use menubar::*;
pub use navigation_menu::*;
pub use pagination::*;
pub use popover::*;
pub use progress::*;
pub use radio_group::*;
pub use resizable::*;
pub use scroll_area::*;
pub use select::*;
pub use separator::*;
pub use sheet::*;
pub use sidebar::*;
pub use skeleton::*;
pub use slider::*;
pub use surfaces::*;
pub use switch::*;
pub use table::*;
pub use tabs::*;
pub use text::*;
pub use textarea::*;
pub use toggle::*;
pub use toggle_group::*;
pub use tooltip::*;
