[package]
name = "arkit_animation_core"
description = "Platform-independent animation model and execution engine for Arkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
oxc_index.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
