/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
  /** Window surface key; defaults to `"main"`. Parent and child must share the same window. */
  windowKey?: string
}

/** Window-scoped request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to the window root. */
export interface NodeMountIntoRootRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export declare function destroy(): void

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function render(bindings: object, slot: NodeContent): void
