/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface DownloadStartResult {
  allow: boolean
  tempPath?: string
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface WebViewInitData {
  url?: string
  id?: string
  style?: WebViewStyle
  javascriptEnabled?: boolean
  devtools?: boolean
  userAgent?: string
  autoplay?: boolean
  initializationScripts?: Array<string>
  headers?: Record<string, string>
  html?: string
  transparent?: boolean
  onDragAndDrop?: (arg: string) => void
  onDownloadStart: OnDownloadStart
  onDownloadEnd: OnDownloadEnd
  onNavigationRequest?: (arg: string) => boolean
  onTitleChange?: (arg: string) => void
}

export interface WebViewStyle {
  x?: number | string
  y?: number | string
  visible?: boolean
  backgroundColor?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: () => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export declare function destroy(): void

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

export declare function render(helper: object, slot: NodeContent): void
