/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function destroy(): void

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

export declare function render(helper: object, slot: NodeContent): void

