[package]
name = "webview_example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
arkit.workspace = true
napi-ohos.workspace = true
napi-derive-ohos.workspace = true

[build-dependencies]
napi-build-ohos.workspace = true
