/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function disposeAllRenders(): void

/**
  * r" Releases only the matching Ability-session transport. A stale
  * r" owner cannot clear endpoints installed for a later session.
  */
export declare function disposeBridge(bridgeOwner: string): void

export declare function disposeRender(renderOwner: string): void

export declare function init(bindings: object, bridgeOwner: string, context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function render(slot: NodeContent, renderOwner: string): void

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  bridgePlugins: Array<BridgePluginDeclaration>
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

/**
  * Structural declaration exported to ArkTS after the native module has configured its Rust
  * plugin registry. The host uses this to select the matching factory automatically and to
  * validate the parts of the contract that affect scheduling. Request and response ABI identity
  * remains pinned by each named N-API type.
  */
export interface BridgePluginDeclaration {
  id: string
  execution: string
  requires: Array<string>
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
}

/** Request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {

}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to this module's component root. */
export interface NodeMountIntoRootRequest {
  handle: number
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}
