[package]
name = "i18n_example"
description = "Type-safe internationalization example for Arkit"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
framework = { workspace = true, features = ["i18n"] }

