[package]
name = "arkit_prelude"
description = "Shared Dioxus and ArkUI prelude for the Arkit crate ecosystem"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_elements.workspace = true
dioxus-core.workspace = true
dioxus-core-macro.workspace = true
dioxus-hooks.workspace = true
dioxus-signals.workspace = true
