/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface WebviewAcknowledgement {
  accepted: boolean
}

/**
  * Event subscriptions derived from Rust callback declarations before a WebView is created.
  *
  * This is transport state, not an ArkTS callback reference. The ArkTS host uses it only to bind
  * the corresponding ArkWeb delegate/event hooks for the new controller.
  */
export interface WebviewCallbackOptions {
  navigationIntercept: boolean
  downloadStart: boolean
  downloadEnd: boolean
  titleChange: boolean
}

/** Controller lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewControllerEvent {
  id: string
  /**
    * Process-unique ArkWeb controller tag generated by the ArkTS host. The public WebView ID
    * remains module-local and is never used as a process-global platform key.
    */
  nativeTag: string
}

export interface WebviewControllerRequest {
  id: string
  visible?: boolean
  color?: string
  url?: string
  html?: string
  headers?: Record<string, string>
  zoom?: number
}

export interface WebviewCreateRequest {
  id: string
  /**
    * Optional opaque container handle issued by the built-in `ohos.node` plugin. When provided,
    * the ArkTS host appends the WebView FrameNode under that container instead of this native
    * module's DefaultXComponent root.
    */
  parentHandle?: number
  url?: string
  html?: string
  style: WebviewStyle
  javascriptEnabled?: boolean
  /**
    * Enables ArkWeb DOM storage (localStorage/sessionStorage). ArkWeb disables it by
    * default; when unset, DOM storage stays disabled, so callers opt in with `true`.
    */
  domStorageAccess?: boolean
  devtools?: boolean
  userAgent?: string
  autoplay?: boolean
  initializationScripts?: Array<WebviewInitializationScript>
  headers?: Record<string, string>
  /**
    * Restores the legacy creation-time transparent-background policy. An explicit style
    * background color takes precedence.
    */
  transparent?: boolean
  eventOptions: WebviewCallbackOptions
}

export interface WebviewCreateResponse {
  id: string
}

/** Completion notification delivered directly through a named N-API callback. */
export interface WebviewDownloadEndEvent {
  id: string
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string
  url: string
  tempPath?: string
  success: boolean
}

/** Request delivered synchronously before ArkWeb starts a download. */
export interface WebviewDownloadStartRequest {
  id: string
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string
  url: string
  tempPath?: string
}

/** Immediate download admission and optional replacement destination. */
export interface WebviewDownloadStartResponse {
  allow: boolean
  tempPath?: string
}

/** Engine lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewEngineLifecycleEvent {
  phase: string
  /**
    * Process-global scheme set sealed before ArkWeb initialization. A module activated after
    * the engine started may join only when every local declaration already exists in this set
    * with identical options.
    */
  schemes: Array<WebviewSchemeDeclaration>
}

export interface WebviewEngineLifecycleResponse {
  accepted: boolean
  schemes: Array<WebviewSchemeDeclaration>
}

/** Response used by one-way named N-API notifications sent directly from ArkTS. */
export interface WebviewEventAcknowledgement {
  accepted: boolean
}

/** A document-start script and the URL rules for pages where ArkWeb may inject it. */
export interface WebviewInitializationScript {
  script: string
  scriptRules: Array<string>
}

/** Request delivered synchronously when ArkWeb asks whether a navigation should be intercepted. */
export interface WebviewNavigationRequest {
  id: string
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string
  url: string
}

/** Synchronous navigation decision. A true value retains ArkWeb's existing intercept semantics. */
export interface WebviewNavigationResponse {
  intercept: boolean
}

export interface WebviewSchemeDeclaration {
  scheme: string
  options: number
}

export interface WebviewScriptRequest {
  id: string
  script: string
}

export interface WebviewScriptResponse {
  result?: string
}

export interface WebviewStringResponse {
  value?: string
}

export interface WebviewStyle {
  x?: number | string
  y?: number | string
  /**
    * Optional width override. Defaults to the full container size; numbers are vp, strings are
    * ArkUI length expressions (for example "30%").
    */
  width?: number | string
  /**
    * Optional height override. Defaults to the full container size; numbers are vp, strings are
    * ArkUI length expressions. Combined with `y` (for example y = "70%", height = "30%") a
    * WebView can be rendered in a corner or along one edge instead of full-screen.
    */
  height?: number | string
  visible?: boolean
  backgroundColor?: string
}

/** Title-change notification delivered directly through a named N-API callback. */
export interface WebviewTitleChangeEvent {
  id: string
  /** Process-unique controller generation used to reject callbacks from a replaced WebView. */
  nativeTag: string
  title: string
}

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  bridgePlugins: Array<BridgePluginDeclaration>
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

/**
  * Structural declaration exported to ArkTS after the native module has configured its Rust
  * plugin registry. The host uses this to select the matching factory automatically and to
  * validate the parts of the contract that affect scheduling. Request and response ABI identity
  * remains pinned by each named N-API type.
  */
export interface BridgePluginDeclaration {
  id: string
  execution: string
  requires: Array<string>
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
}

/** Request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {

}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to this module's component root. */
export interface NodeMountIntoRootRequest {
  handle: number
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export declare function disposeAllRenders(): void

/**
  * r" Releases only the matching Ability-session transport. A stale
  * r" owner cannot clear endpoints installed for a later session.
  */
export declare function disposeBridge(bridgeOwner: string): void

export declare function disposeRender(renderOwner: string): void

export declare function init(bindings: object, bridgeOwner: string, context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function render(slot: NodeContent, renderOwner: string): void
