/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface WebviewAcknowledgement {
  accepted: boolean
}

/**
  * Event subscriptions derived from Rust callback declarations before a WebView is created.
  *
  * This is transport state, not an ArkTS callback reference. The ArkTS host uses it only to bind
  * the corresponding ArkWeb delegate/event hooks for the new controller.
  */
export interface WebviewCallbackOptions {
  navigationIntercept: boolean
  downloadStart: boolean
  downloadEnd: boolean
  titleChange: boolean
}

/** Controller lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewControllerEvent {
  id: string
}

export interface WebviewControllerRequest {
  id: string
  visible?: boolean
  color?: string
  url?: string
  html?: string
  headers?: Record<string, string>
  zoom?: number
}

export interface WebviewCreateRequest {
  id: string
  /**
    * Optional window surface key the WebView mounts into. Defaults to `"main"` (the default
    * window's `DefaultXComponent`); sub-window instances register under their own `windowKey`.
    */
  windowKey?: string
  /**
    * Optional opaque container handle issued by the built-in `ohos.node` plugin. When provided,
    * the ArkTS host appends the WebView FrameNode under that container instead of the window
    * root, so an RS-layer node tree can adopt WebViews as children. Absent = full-bleed window
    * root mount.
    */
  parentHandle?: number
  url?: string
  html?: string
  style: WebviewStyle
  javascriptEnabled?: boolean
  devtools?: boolean
  userAgent?: string
  autoplay?: boolean
  initializationScripts?: Array<WebviewInitializationScript>
  headers?: Record<string, string>
  /**
    * Restores the legacy creation-time transparent-background policy. An explicit style
    * background color takes precedence.
    */
  transparent?: boolean
  eventOptions: WebviewCallbackOptions
}

export interface WebviewCreateResponse {
  id: string
}

/** Completion notification delivered directly through a named N-API callback. */
export interface WebviewDownloadEndEvent {
  id: string
  url: string
  tempPath?: string
  success: boolean
}

/** Request delivered synchronously before ArkWeb starts a download. */
export interface WebviewDownloadStartRequest {
  id: string
  url: string
  tempPath?: string
}

/** Immediate download admission and optional replacement destination. */
export interface WebviewDownloadStartResponse {
  allow: boolean
  tempPath?: string
}

/** Engine lifecycle signal delivered directly from the ArkTS WebView host. */
export interface WebviewEngineLifecycleEvent {
  phase: string
}

/** Response used by one-way named N-API notifications sent directly from ArkTS. */
export interface WebviewEventAcknowledgement {
  accepted: boolean
}

/** A document-start script and the URL rules for pages where ArkWeb may inject it. */
export interface WebviewInitializationScript {
  script: string
  scriptRules: Array<string>
}

/** Request delivered synchronously when ArkWeb asks whether a navigation should be intercepted. */
export interface WebviewNavigationRequest {
  id: string
  url: string
}

/** Synchronous navigation decision. A true value retains ArkWeb's existing intercept semantics. */
export interface WebviewNavigationResponse {
  intercept: boolean
}

export interface WebviewScriptRequest {
  id: string
  script: string
}

export interface WebviewScriptResponse {
  result?: string
}

export interface WebviewStringResponse {
  value?: string
}

export interface WebviewStyle {
  x?: number | string
  y?: number | string
  /**
    * Optional width override. Defaults to the full container size; numbers are vp, strings are
    * ArkUI length expressions (for example "30%").
    */
  width?: number | string
  /**
    * Optional height override. Defaults to the full container size; numbers are vp, strings are
    * ArkUI length expressions. Combined with `y` (for example y = "70%", height = "30%") a
    * WebView can be rendered in a corner or along one edge instead of full-screen.
    */
  height?: number | string
  visible?: boolean
  backgroundColor?: string
}

/** Title-change notification delivered directly through a named N-API callback. */
export interface WebviewTitleChangeEvent {
  id: string
  title: string
}

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
  /** Window surface key; defaults to `"main"`. Parent and child must share the same window. */
  windowKey?: string
}

/** Window-scoped request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to the window root. */
export interface NodeMountIntoRootRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

export declare function destroy(): void

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

/** r" ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/**
  * r" Synchronous ArkTS platform callback -> Rust plugin decision port.
  * r"
  * r" The N-API value is scoped to this call; the returned value is
  * r" produced before ArkTS resumes the originating platform callback.
  */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function render(bindings: object, slot: NodeContent): void

