[package]
name = "arkit_shadcn"
description = "Shadcn-style native ArkUI components for Arkit applications"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_animation = { workspace = true }
arkit_prelude = { workspace = true }
arkit_icon = { workspace = true }
arkit_hooks = { workspace = true }
arkit_runtime = { workspace = true }
ohos-display-binding = { workspace = true }
tokio = { workspace = true }

[lib]
