[package]
name = "arkit_animation"
description = "Animation engine and ArkUI rendering adapters for Arkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
arkit_animation_core.workspace = true
arkit_prelude.workspace = true
arkit_hooks.workspace = true
ohos-arkui-binding.workspace = true
ohos-arkui-sys.workspace = true
ohos-hilog-binding.workspace = true
oxc_index.workspace = true
rustc-hash.workspace = true
