[package]
name = "arkit_elements"
description = "Dioxus element and attribute definitions for native ArkUI components"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "dioxus_elements"

[dependencies]
dioxus-core.workspace = true
